const strategies = {longCall:{id:'1',options:[{
        id:'1',
        mony:'ALL',
        type:'C',
        pos:'L',
    }],img:require('../assets/longCall.png'),id:1},
    longPut:{id:'2',options:[{
        id:'1',
        mony:'ALL',
        type:'P',
        pos:'L'
    }],img:require('../assets/longPut.png'),id:2},
    shortCall:{id:'3',options:[{
        id:'1',
        mony:'ALL',
        type:'C',
        pos:'S'
    }],img:require('../assets/shortCall.png'),id:3},
    shortPut:{id:'4',options:[{
        id:'1',
        mony:'ALL',
        type:'P',
        pos:'S'
    }],img:require('../assets/shortPut.png'),id:4},
    bullCallSpread:{id:'5',options:[{
        id:'1',
        mony:'ITM',
        type:'C',
        pos:'L'
    },{
        id:'2',
        mony:'OTM',
        type:'C',
        pos:'S'
    }],img:require('../assets/bullCallSpread.png'),id:5},
    bearCallSpread:{id:'6',options:[{
        id:'1',
        mony:'ITM',
        type:'C',
        pos:'S'
    },{
        id:'2',
        mony:'OTM',
        type:'C',
        pos:'L'
    }],img:require('../assets/bearCallSpread.png'),id:6},
    callRatioBackSpread:{id:'7',options:[{
        id:'1',
        mony:'ITM',
        type:'C',
        pos:'S'
    },{
        id:'2',
        mony:'OTM',
        type:'C',
        pos:'L'
    },{
        id:'3',
        mony:'OTM',
        type:'C',
        pos:'L'
    }],img:require('../assets/callRatioBackSpread.png'),id:7},
    putRatioBackSpread:{id:'8',options:[{
        id:'1',
        mony:'ITM',
        type:'P',
        pos:'S'
    },{
        id:'2',
        mony:'OTM',
        type:'P',
        pos:'L'
    },{
        id:'3',
        mony:'OTM',
        type:'P',
        pos:'L'
    }],img:require('../assets/putRatioBackSpread.png'),id:8},
    bearCallLadder:{id:'9',options:[{
        id:'1',
        mony:'ITM',
        type:'C',
        pos:'S'
    },{
        id:'2',
        mony:'OTM',
        type:'C',
        pos:'L'
    },{
        id:'3',
        mony:'ITM',
        type:'C',
        pos:'L'
    }],img:require('../assets/bearCallLadder.png'),id:9},
    bearPutLadder:{id:'10',options:[{
        id:'1',
        mony:'ITM',
        type:'P',
        pos:'L'
    },{
        id:'2',
        mony:'OTM',
        type:'C',
        pos:'L'
    },{
        id:'3',
        mony:'ITM',
        type:'P',
        pos:'S'
    }],img:require('../assets/bullPutLadder.png'),id:10},
    longStraddle:{id:'11',options:[{
        id:'1',
        mony:'ITM',
        type:'C',
        pos:'L'
    },{
        id:'2',
        mony:'ITM',
        type:'P',
        pos:'L'
    }],img:require('../assets/longStraddle.png'),id:11},
    shortStraddle:{id:'12',options:[{
        id:'1',
        mony:'ITM',
        type:'C',
        pos:'S'
    },{
        id:'2',
        mony:'ITM',
        type:'P',
        pos:'S'
    }],img:require('../assets/shortStraddle.png'),id:12},
    longStraddle:{id:'13',options:[{
        id:'1',
        mony:'OTM',
        type:'C',
        pos:'L'
    },{
        id:'2',
        mony:'OTM',
        type:'P',
        pos:'L'
    }],img:require('../assets/longStraddle.png'),id:13},
    shortStrangle:{id:'14',options:[{
        id:'1',
        mony:'OTM',
        type:'C',
        pos:'S'
    },{
        id:'2',
        mony:'OTM',
        type:'P',
        pos:'S'
    }],img:require('../assets/shortStrangle.png'),id:14},
    ironCondor:{id:'15',options:[{
        id:'1',
        mony:'OTM',
        type:'C',
        pos:'S'
    },{
        id:'2',
        mony:'OTM',
        type:'P',
        pos:'S'
    },{
        id:'3',
        mony:'OTM',
        type:'C',
        pos:'L'
    },{
        id:'4',
        mony:'OTM',
        type:'P',
        pos:'L'
    }],img:require('../assets/ironCondor.png'),id:15},
    reverseIronCondor:{id:'16',options:[{
        id:'1',
        mony:'OTM',
        type:'C',
        pos:'L'
    },{
        id:'2',
        mony:'OTM',
        type:'P',
        pos:'L'
    },{
        id:'3',
        mony:'OTM',
        type:'C',
        pos:'S'
    },{
        id:'4',
        mony:'OTM',
        type:'P',
        pos:'S'
    }],img:require('../assets/reverseIronCondor.png'),id:16}
}

export default strategies